In [2]:
import torch
x = torch.rand(5,3)
print(x)

tensor([[0.4426, 0.7265, 0.6348],
        [0.5177, 0.7965, 0.5589],
        [0.8741, 0.9099, 0.3961],
        [0.1481, 0.2265, 0.7136],
        [0.9270, 0.3859, 0.9773]])


In [12]:
target = torch.rand(10)
print(target)
target = target.view(1,-1)
print(target)

tensor([0.7356, 0.0489, 0.8893, 0.6932, 0.2773, 0.6001, 0.1178, 0.4417, 0.3156,
        0.9175])
tensor([[0.7356, 0.0489, 0.8893, 0.6932, 0.2773, 0.6001, 0.1178, 0.4417, 0.3156,
         0.9175]])


In [9]:
torch.rand(10,1)

tensor([[0.1465],
        [0.5214],
        [0.6784],
        [0.3588],
        [0.8290],
        [0.0869],
        [0.6731],
        [0.9229],
        [0.5465],
        [0.4196]])

In [11]:
torch.rand(10)

tensor([0.6106, 0.5315, 0.0790, 0.8435, 0.9840, 0.5197, 0.8708, 0.2099, 0.3677,
        0.1350])

In [15]:
target.reshape(2,5)

tensor([[0.7356, 0.0489, 0.8893, 0.6932, 0.2773],
        [0.6001, 0.1178, 0.4417, 0.3156, 0.9175]])

In [16]:
target.view(2,5)

tensor([[0.7356, 0.0489, 0.8893, 0.6932, 0.2773],
        [0.6001, 0.1178, 0.4417, 0.3156, 0.9175]])