# 1. 创建

In [1]:
from __future__ import print_function
import torch

In [3]:
# 构造一个2*3的矩阵，不初始化
print(torch.empty(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# 构造一个随机初始化的矩阵
print(torch.rand(2,3))

tensor([[0.1257, 0.6754, 0.7611],
        [0.0973, 0.4560, 0.9570]])


In [5]:
# 构造一个矩阵全为 0，而且数据类型是 long.
print(torch.zeros(2,3,dtype=torch.long))

tensor([[0, 0, 0],
        [0, 0, 0]])


In [9]:
## 构造一个张量，直接使用数据
print(torch.tensor([5.5,3]))

tensor([5.5000, 3.0000])


In [18]:
## 根据已有的tensor建立新的tensor
x = torch.rand(2,4,dtype=torch.double) 
print(x)
print(torch.rand_like(x,dtype=torch.float))

tensor([[0.2354, 0.8545, 0.7127, 0.8176],
        [0.6332, 0.6257, 0.8886, 0.7906]], dtype=torch.float64)
tensor([[0.1845, 0.4012, 0.7029, 0.3101],
        [0.1659, 0.3938, 0.3084, 0.4130]])


# 2. 操作

In [11]:
# 加法
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x)
print(y)
print(x+y)
print(torch.add(x,y))

tensor([[0.7562, 0.8912, 0.1928],
        [0.8978, 0.6429, 0.6057]])
tensor([[0.9988, 0.4427, 0.7222],
        [0.0299, 0.3176, 0.9730]])
tensor([[1.7549, 1.3339, 0.9150],
        [0.9277, 0.9605, 1.5787]])
tensor([[1.7549, 1.3339, 0.9150],
        [0.9277, 0.9605, 1.5787]])


In [12]:
# 把x加到y上 【关于tensor的原地操作函数都有一个后缀‘_’，例如y.add_(x);y.copy_(y)】
print(y)
y.add_(x)
print(y)

tensor([[0.9988, 0.4427, 0.7222],
        [0.0299, 0.3176, 0.9730]])
tensor([[1.7549, 1.3339, 0.9150],
        [0.9277, 0.9605, 1.5787]])


In [16]:
# 输出 第2行第2列；第2行；第2列
print(y[1][1],y[1:2],y[:,1])

tensor(0.9605) tensor([[0.9277, 0.9605, 1.5787]]) tensor([1.3339, 0.9605])


# 3. Tensor与NumPy数组

In [4]:
## tensor 转化为 numpy数组
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [5]:
# 当修改a的值，b的值也在跟着变化，说明a与b共享底层内存位置
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [7]:
# numpy转化为Tensor 【CPU上的所有张量(CharTensor除外)都支持与Numpy的相互转换】
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)// a和b是共享内存空间的。如果是 a = a+1的话，a和b是不共享内存空间的
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [3]:
# CUDA Tensors
# torch.cuda.is_available() 判断是否有 gpu
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# tensor变量使用 .to方法可以放到 device 上