In [58]:
import pandas as pd

data = pd.read_csv("1_feature_selected.csv",nrows = 500,header=None)
data

0         1      2        3        4         5         6         7   \
0    37     0.341  0.256  16.1160  0.35736 -2.770400   0.41784    4.1784   
1    37     0.913  0.086  12.4950  0.26504 -2.830000   0.00000  156.7900   
2    37     0.733  0.111  16.0340  0.99118 -0.031436  32.12200  143.8500   
3    37     0.448  0.094   6.8213  0.59647 -2.810500  17.36000   76.6380   
4    37     0.519  0.056  13.8660  0.67819 -2.808300  74.82100  275.5700   
..   ..       ...    ...      ...      ...       ...       ...       ...   
495   1 -1627.400  0.091  14.4380  0.57212 -2.913100  65.36900  138.1800   
496   1    17.832  0.230   4.1952  0.90732 -1.142000   2.84390   12.4230   
497   1     0.489  0.069   0.0000  1.00000  0.000000   0.00000    0.0000   
498   1     3.850  1.434  16.0400  0.80749  1.741500   4.14940    8.8246   
499   1     1.949  1.253  15.3080  0.89276  1.757000   8.18660   12.8270   

           8             9   ...            14            15        16  \
0    2719.200 -604180.00000  ...  0.000000e+00  0.000000e+00  0.124440   
1     502.370  -26083.00000  ...  0.000000e+00  0.000000e+00  0.406210   
2     263.580  -52140.00000  ... -8.025300e-01 -1.165800e-01  0.000000   
3     230.620  -10012.00000  ...  0.000000e+00  1.012800e-01  0.570430   
4     993.210 -126180.00000  ... -9.671400e-02  0.000000e+00  0.001099   
..        ...           ...  ...           ...           ...       ...   
495   768.290  -46513.00000  ...  3.110000e-16  5.025000e-01  1.519800   
496   329.010   -7304.90000  ... -7.280000e-02 -2.220000e-16  0.001416   
497     0.000  -37224.24369  ...  0.000000e+00  0.000000e+00  0.000000   
498    28.907    -537.58000  ... -3.000600e-01 -2.074500e-01 -0.053714   
499    25.590    -809.40000  ... -1.304200e-01 -5.123500e-02  0.034157   

           17       18        19       20            21    22        23  
0   -2.581200  16.1320  0.998980   63.018   -432.240000  0.32  0.044444  
1   -2.199400  12.5960  0.991970  146.470   5117.700000  0.60  0.088889  
2    0.086288  16.2030  0.989590  145.970  -3563.500000  0.48  0.044444  
3   -2.723100   6.9674  0.979020   74.122  -4604.100000  0.40  0.044444  
4   -2.717000  13.8710  0.999650  247.690 -21377.000000  0.44  0.044444  
..        ...      ...       ...      ...           ...   ...       ...  
495 -2.736300  15.0510  0.959290  165.390  -2107.200000  0.65  0.222220  
496 -0.941450   4.2232  0.993370   18.362    827.900000  0.35  0.088889  
497  0.000000   0.0000  0.912236    0.000   7581.551329  0.27  0.088889  
498  1.545400  16.4800  0.973290   11.493   -115.440000  0.68  0.200000  
499  1.660200  15.6930  0.975510   12.524     51.968000  0.50  0.155560  

[500 rows x 24 columns]

In [59]:
import numpy as np
data[0] = np.where(data[0]==37,1,0)

In [69]:
x = data.iloc[:,1:].values
y = data[0].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [67]:
x.values

array([[ 3.41000000e-01,  2.56000000e-01,  1.61160000e+01, ...,
        -4.32240000e+02,  3.20000000e-01,  4.44440000e-02],
       [ 9.13000000e-01,  8.60000000e-02,  1.24950000e+01, ...,
         5.11770000e+03,  6.00000000e-01,  8.88890000e-02],
       [ 7.33000000e-01,  1.11000000e-01,  1.60340000e+01, ...,
        -3.56350000e+03,  4.80000000e-01,  4.44440000e-02],
       ...,
       [ 4.89000000e-01,  6.90000000e-02,  0.00000000e+00, ...,
         7.58155133e+03,  2.70000000e-01,  8.88890000e-02],
       [ 3.85000000e+00,  1.43400000e+00,  1.60400000e+01, ...,
        -1.15440000e+02,  6.80000000e-01,  2.00000000e-01],
       [ 1.94900000e+00,  1.25300000e+00,  1.53080000e+01, ...,
         5.19680000e+01,  5.00000000e-01,  1.55560000e-01]])

In [70]:
import torch
import torch.nn.functional as F     # 激励函数都在这
# 101 -- 1024 是训练数据，1--100是测试数据
trainX = torch.Tensor(x)
trainY = torch.LongTensor(y)

In [71]:
trainY

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [90]:
trainX

tensor([[ 3.4100e-01,  2.5600e-01,  1.6116e+01,  ..., -4.3224e+02,
          3.2000e-01,  4.4444e-02],
        [ 9.1300e-01,  8.6000e-02,  1.2495e+01,  ...,  5.1177e+03,
          6.0000e-01,  8.8889e-02],
        [ 7.3300e-01,  1.1100e-01,  1.6034e+01,  ..., -3.5635e+03,
          4.8000e-01,  4.4444e-02],
        ...,
        [ 4.8900e-01,  6.9000e-02,  0.0000e+00,  ...,  7.5816e+03,
          2.7000e-01,  8.8889e-02],
        [ 3.8500e+00,  1.4340e+00,  1.6040e+01,  ..., -1.1544e+02,
          6.8000e-01,  2.0000e-01],
        [ 1.9490e+00,  1.2530e+00,  1.5308e+01,  ...,  5.1968e+01,
          5.0000e-01,  1.5556e-01]])

In [133]:
class RNN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.rnn=torch.nn.LSTM(
            input_size=23,
            hidden_size=64,
            num_layers=2,
            batch_first=True
        )
        self.out=torch.nn.Linear(in_features=64,out_features=2)

    def forward(self,x):
        # 以下关于shape的注释只针对单向
        # output: [batch_size, time_step, hidden_size]
        # h_n: [num_layers,batch_size, hidden_size] # 虽然LSTM的batch_first为True,但是h_n/c_n的第一维还是num_layers
        # c_n: 同h_n
        print(x)
        output,(h_n,c_n)=self.rnn(x)
        print(output.size())
        # output_in_last_timestep=output[:,-1,:] # 也是可以的
        output_in_last_timestep=h_n[-1,:]
        # print(output_in_last_timestep.equal(output[:,-1,:])) #ture
        x=self.out(output_in_last_timestep)
        return x
userNet = RNN() # 10维的特征，100个隐藏节点，输出4个类别

In [134]:
userNet

RNN(
  (rnn): LSTM(23, 64, num_layers=2, batch_first=True)
  (out): Linear(in_features=64, out_features=2, bias=True)
)

In [135]:
# 训练代码
loss_fn = torch.nn.CrossEntropyLoss() # 损失函数
optimizer = torch.optim.Adam(userNet.parameters(),lr=3e-14)#优化器使用Adam,学习率为0.05

for t in range(1000):
    out = userNet(trainX)     # 喂给 net 训练数据 x, 输出分析值

    loss = loss_fn(out, trainY)     # 计算两者的误差
    if t % 100 == 0:
        print("Epoch",t,loss.item())
    optimizer.zero_grad()   # 清空上一步的残余更新参数值
    loss.backward()         # 误差反向传播, 计算参数更新值
    optimizer.step()        # 将参数更新值施加到 net 的 parameters 上

tensor([[ 3.4100e-01,  2.5600e-01,  1.6116e+01,  ..., -4.3224e+02,
          3.2000e-01,  4.4444e-02],
        [ 9.1300e-01,  8.6000e-02,  1.2495e+01,  ...,  5.1177e+03,
          6.0000e-01,  8.8889e-02],
        [ 7.3300e-01,  1.1100e-01,  1.6034e+01,  ..., -3.5635e+03,
          4.8000e-01,  4.4444e-02],
        ...,
        [ 4.8900e-01,  6.9000e-02,  0.0000e+00,  ...,  7.5816e+03,
          2.7000e-01,  8.8889e-02],
        [ 3.8500e+00,  1.4340e+00,  1.6040e+01,  ..., -1.1544e+02,
          6.8000e-01,  2.0000e-01],
        [ 1.9490e+00,  1.2530e+00,  1.5308e+01,  ...,  5.1968e+01,
          5.0000e-01,  1.5556e-01]])


RuntimeError: input must have 3 dimensions, got 2

In [98]:
trainX.shape

torch.Size([500, 23])

In [99]:
trainX[0]

tensor([ 3.4100e-01,  2.5600e-01,  1.6116e+01,  3.5736e-01, -2.7704e+00,
         4.1784e-01,  4.1784e+00,  2.7192e+03, -6.0418e+05, -4.3224e+02,
         6.0332e+05,  4.1784e+00,  1.7777e-01,  0.0000e+00,  0.0000e+00,
         1.2444e-01, -2.5812e+00,  1.6132e+01,  9.9898e-01,  6.3018e+01,
        -4.3224e+02,  3.2000e-01,  4.4444e-02])